### ISSUE TITLE
Sync portfolios with GitHub doesn't work

### ISSUE THREAD

**Issue by billhong6981** [gitconnected/gitconnected-feedback#11]
same as the topic above

**Comment by treyhuffine** [comment]
Thanks for submitting an issue @billhong6981. Could you describe the issue you're seeing a little more, and I'll look into as soon as I understand the bug.

**Comment by billhong6981** [comment]
Hi Trey
Nice work man. I used gitconnected.com to build my portfolio api, after creating my profile, then I realized that some project in github are not necessary now, I go to delete those repos and come back gitconnected to sync but the old project name still there. 

As pictures above, I don’t have the first repo “gitconnected-feedback”, the second repo “github-slideshow” has been deleted, but still there. 
One more thing is: I clone your repo “build an portfolio website using react” and run it in vagrant virtual machine terminal, but it failed in compiling. What am I wrong?

Have a good weekend 
Bill

**Comment by treyhuffine** [comment]
I really appreciate the kind words and taking the time to write such detailed feedback. I excited to help out and get it resolved!

My original intent was that syncing projects with GitHub would purely be additive, but I can take another look at this if it isn't preferred or unintuitive. Since in `/projects`, users can add non-opensource projects from outside of GitHub or things on the GitHub side can change (repos can be deleted, become private, be moved), I didn't want to change the details on the gitconnected side since devs may still want to display a project in their profile or their portfolio even if it didn't explicitly exist in their GitHub anymore. My plan was that once the projects were imported to gitconnected.com, users could manage the visibility of them with "Feature" and "Unfeature" buttons in their project board under `/projects`. 

<img width="1275" alt="Screen Shot 2019-12-16 at 12 07 20 PM" src="https://user-images.githubusercontent.com/11709986/70931966-3d5ed200-1ffe-11ea-8a83-68d7da941855.png">

I'm not seeing the images, but I would happy to look into that if you're able to attach them.

Also I've tried on 2 different machines and can't reproduce the issue with the portfolio repo. If you can post a screen shot of the error output, I'm happy to take a look at that as well. I added instructions to the repo if you can confirm you ran all the steps:
```
git clone git@github.com:treyhuffine/portfolio-create-react-app.git
cd portfolio-create-react-app
yarn install
yarn start
```

**Comment by billhong6981** [comment]
Hi, Trey
Thanks for your explanation, now I understand your point. thanks again.
I tried to run the clone project in Ubuntu 16.04, but it fails to compile.
[image: Screen Shot 2019-12-16 at 8.22.09 PM.png]

But I try to run the App in MacBook terminal, yes, it works. cool!

Regards
Bill

**Comment by treyhuffine** [comment]
Unfortunately I'm inclined to think that's a cross-environment bug with Create React App which is a bummer. I didn't try to get too adventurous with how I used it, and I can't think of what else in the code would cause it.

Thanks again for the help, and I'm excited to have you in the community! I'm going to continue to iterate on this feature, so if you ever have any more feedback, I would love to hear it :)

**Comment by treyhuffine** [comment]
Going to close these for now. Feel free to create another if you have more feedback or a question :)
