### ISSUE TITLE
Loss of new email addresses

### ISSUE THREAD

**Issue by gabolaev** [gitconnected/gitconnected-feedback#19]
I just added a new email address to my profile on GitHub, but it didn't appear on gitconnected profile settings.

btw, I managed to make it primary via self-made cURL request, although it's definitely an issue, cuz there isn't still my new email address in the list

![image](https://user-images.githubusercontent.com/10693243/81860796-ebe84e00-956f-11ea-839e-325701aa9de5.png)
![image](https://user-images.githubusercontent.com/10693243/81860915-1b975600-9570-11ea-860c-91ca0f652d6d.png)

**Comment by treyhuffine** [comment]
@gabolaev thanks for reporting, that's definitely a bug. Did you also log out and log back in and still no luck?

When you made the cURL request, did you have to provide the cookie as well or are you saying that you could change your email without the cookie?

I'll look into this ASAP, but if you want to give me your desired email, I can update it manually so that you don't have to wait for a fix.

**Comment by gabolaev** [comment]
@treyhuffine relogin works! but yeah, it's better to fix that

thanks for quick answer!

**Comment by gabolaev** [comment]
@treyhuffine about cookies

I used Chrome built-in “copy as cURL” feature for the XHR request, which switches the primary email address, and I manually changed the new email field, so I haven't done any cookie manipulations because they were simply copied with the entire request data (headers, body, etc)

**Comment by treyhuffine** [comment]
Thanks for the info, and glad we could get it fixed! I'll add fixing this issue to our pipeline.
