### ISSUE TITLE
Show Git Private Repos in Projects

### ISSUE THREAD

**Issue by itsharsh** [gitconnected/gitconnected-feedback#28]

**Comment by treyhuffine** [comment]
Hi @itsharsh it should already be pulling repos from organizations unless there was a change to the GitHub API. Can you share a link to the project you were expecting

**Comment by itsharsh** [comment]
@treyhuffine 
Yes, you are right, repos are being fetched from organisations.

Correction: It's not showing any private repo from the private or organization account.

**Comment by treyhuffine** [comment]
Thanks for the insight. At the moment, I don't want to ask users for access to private repos through OAuth, because I think people will be hesitant to provide. I would recommend using the "Add a project" button on the `/projects` route where you can input the details without actually providing any private access.

<img width="1439" alt="Screen Shot 2020-07-24 at 11 38 22 AM" src="https://user-images.githubusercontent.com/11709986/88414333-4c7edd00-cda2-11ea-834a-ae5cbf0c6d73.png">

**Comment by itsharsh** [comment]
Yeah, I'm using that already.
But, it would have been easier if all private repos are fetched and shown on the resume.
My objective is to list that private project on the resume, with the demo link only.

**Comment by treyhuffine** [comment]
Unfortunately, I don't think we'll be prioritizing this at the moment. We used GitHub to pull private repos in the past, and people complained of needing to give access to private projects. It also has some potential legal issues if we gain access to private repos when the companies that host them haven't specifically condoned it.
