### ISSUE TITLE
Bug on Import JSON

### ISSUE THREAD

**Issue by gitstercode** [gitconnected/gitconnected-feedback#58]
Import JSON adding double entries in the UI/exported PDF.
For e.g theres a skill Python already, if I import JSON and Python gets added again. And after next import there will be three Python skills added.
Same thing for other items like Experience.

Expectation is that, it replaces the full profile with latest JSON import.

**Comment by treyhuffine** [comment]
I errored on the side of being non-destructive because I think it could be very frustrating to add a bunch of content and then have it be removed unexpectedly if you performed a resume import. Since it’s much more time-consuming to add content it is than delete content already on the profile, it’s intentionally done this way. I’ll think on the most effective way to handle this so it can be the best of both worlds, but at the moment, you need to go through at press the delete button on the items that you don’t want.

Feel free to re-open this if you would like to discuss it further!
